name: modelling_earth
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - xarray
    # Optional dependencies
    - matplotlib
    - jupyter
    - jupyterlab
    - jupytext
    - ipython
    - pip:
        - tables
