name: modelling_earth
channels:
    - conda-forge
dependencies:
    - python=3.7.7
    - pip
    - numpy
    - scipy
    - xarray=0.15.1
    - pandas
    - pytables
    # Optional dependencies
    - matplotlib
    - jupyter
    - jupyterlab
    - jupytext
    - ipython
    - dask
    # Development requirements
    - black
    - pylint
    - flake8
